#!/bin/bash
#####################################################################
# The script accept IP as the first argument and do ping to this IP #
#####################################################################
ip=$1
host=${NODE_NAME}
[[ -z "${nost}" ]] && host=$(hostname -s)
[[ -z "$ip" ]] && echo "Usage: $0 ip-address" && exit 127
[[ $ip =~ ^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]] \
&& RTT=$(ping -4w1 -qc2 ${ip}|grep -E 'round-trip|rtt'|awk '{print $4}'| awk -F/ '{print $3}') \
&& echo "${host}:${RTT}"

